<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link href="bower_components/bootstrap/dist/css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css">
        <script src="bower_components/jquery/dist/jquery.min.js" type="text/javascript"></script>
        <script src="bower_components/mustache.js/mustache.min.js" type="text/javascript"></script>
        <script src="bower_components/StreamTable.js/stream_table.min.js" type="text/javascript"></script>
        <script src="js/index.js" type="text/javascript"></script>
        <style>
            body{
                margin-top: 10px;
                background-color: #eeeeee;
            }

            .title{
                margin-bottom: 20px;
                color: #b94a48;
                border-bottom: 5px solid #b94a48;
            }

            .title .glyphicon{
                font-size: 30px;
                color: #000;
            }

            .title h1{
                font-weight: bold;
            }

            .title .lead{
                margin-bottom: 20px;
                font-size: 21px;
                font-weight: 200;
                line-height: 1.4;
            }

            .example{
                max-width: 900px;
                margin: auto;
            }

            .st_search{
                max-width: 200px;
                float: right;
                margin-bottom: 10px;
            }

            .pagination{
                float: right;
                margin-top: 0px;
            }

            .pagination li.active a{
                background-color: #DCDCDC;
            }

            .st_per_page{
                width: 50px;
                height: 34px !important;
                float: right;
                margin-right: 20px;
            }

            .record_count {
                margin-left: 20px;
            }

            #spinner {
                font-size: 18px;
                margin-left: 10px;
                display: none;
            }

            #found{
                margin-left: 10px;
                font-size: 16px;
                line-height: 33px;
            }

            .example .progress{
                width: 400px;
                display: inline-block;
                height: 32px;
                line-height: 34px;
                float: left;
                background-color: #90EFC4;
            }

            .example .progress .progress-bar{
                font-size: 20px;
                color: #8B0000;
            }
        </style>
    </head>
    <body>
    <div class="container">
        <div class='example'>
            <div class="title">
                <h1>Spotahome Development Test</span></h1>
                <p>Built with Slim Framework 3 and StreamTable.js</p>
            </div>
            <span id="spinner" class="glyphicon glyphicon-refresh"></span>
            <a href="#" class='record_count'>Records <span class="badge"></span></a>
            <span id="found" class="label label-info"></span>
            <table id="stream_table" class='table table-striped table-bordered'>
                <thead>
                <tr>
                    <th>#</th>
                    <th></th>
                    <th data-sort="id:asc">ID</th>
                    <th data-sort="title:asc">Title</th>
                    <th data-sort="city:asc">City</th>
                </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
            <div id="summary"><div>
                </div>
            </div>

            <script id="template" type="text/html">
                <tr>
                    <td>{{index}}</td>
                    <td><img src="{{ record.picture }}" width="100" /></td>
                    <td>{{record.id}}</td>
                    <td><a href="{{record.url}}">{{record.title}}</a></td>
                    <td>{{record.city}}</td>
                </tr>
            </script>

    </body></html>
