<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href="bower_components/bootstrap/dist/css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css">
        <link href="css/index.css" media="screen" rel="stylesheet" type="text/css">
        <script src="bower_components/jquery/dist/jquery.min.js" type="text/javascript"></script>
        <script src="bower_components/mustache.js/mustache.min.js" type="text/javascript"></script>
        <script src="bower_components/StreamTable.js/stream_table.min.js" type="text/javascript"></script>
        <script src="js/index.js" type="text/javascript"></script>
    </head>
    <body>
    <div class="container">
        <div class='example'>
            <div class="title">
                <h1>Spotahome Development Test</span></h1>
                <p>Built with Slim Framework 3 and StreamTable.js</p>
            </div>
            <span id="found" class="label label-info"></span>
            <table id="stream_table" class='table table-striped table-bordered'>
                <thead>
                <tr>
                    <th>#</th>
                    <th></th>
                    <th data-sort="id:asc">ID</th>
                    <th data-sort="title:asc">Title</th>
                    <th data-sort="city:asc">City</th>
                </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
            <div id="summary"><div>
                </div>
            </div>

            <script id="template" type="text/html">
                <tr>
                    <td>{{index}}</td>
                    <td><img src="{{ record.picture }}" width="100" /></td>
                    <td>{{record.id}}</td>
                    <td><a href="{{record.url}}">{{record.title}}</a></td>
                    <td>{{record.city}}</td>
                </tr>
            </script>

    </body></html>
